require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Naming/FileName:
  Exclude:
    - '**/r18n-desktop.rb'
    - '**/r18n-desktop_spec.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

RSpec/NestedGroups:
  Enabled: false

# TODO: fix offenses and enable cops

Metrics/ClassLength:
  Exclude:
    - 'lib/r18n-desktop/win32.rb'
