require:
  - rubocop-performance
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Naming/FileName:
  Exclude:
    - '**/r18n-desktop.rb'
    - '**/r18n-desktop_spec.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

# TODO: fix offenses and enable cops

Metrics/ClassLength:
  Exclude:
    - 'lib/r18n-desktop/win32.rb'
